/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.assistaff.GUI;

/**
 *
 * @author cc
 */
public class GUICredencial extends javax.swing.JFrame {

    /**
     * Creates new form GUICredencial
     */
    public GUICredencial() {
        initComponents();
        //super.setUndecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTitulo = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        PanelCancelar = new javax.swing.JPanel();
        LabelCancelar = new javax.swing.JLabel();
        PanelCredencialFront = new javax.swing.JPanel();
        LabelLogo = new javax.swing.JLabel();
        LabelUserImage = new javax.swing.JLabel();
        LabelNombre = new javax.swing.JLabel();
        LabelTurno = new javax.swing.JLabel();
        PanelCredencialBack = new javax.swing.JPanel();
        LabelQR = new javax.swing.JLabel();
        PanelImprimir = new javax.swing.JPanel();
        LabelImprimir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelTitulo.setBackground(new java.awt.Color(21, 100, 191));

        LabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LabelTitulo.setText("Credencial");
        LabelTitulo.setToolTipText("");
        LabelTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        PanelCancelar.setBackground(new java.awt.Color(255, 0, 0));

        LabelCancelar.setBackground(new java.awt.Color(0, 0, 0));
        LabelCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assistaff/resources/cancel.png"))); // NOI18N
        LabelCancelar.setToolTipText("");

        javax.swing.GroupLayout PanelCancelarLayout = new javax.swing.GroupLayout(PanelCancelar);
        PanelCancelar.setLayout(PanelCancelarLayout);
        PanelCancelarLayout.setHorizontalGroup(
            PanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        PanelCancelarLayout.setVerticalGroup(
            PanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(PanelCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PanelCredencialFront.setBackground(new java.awt.Color(0, 0, 0));

        LabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assistaff/resources/LogoForHome.png"))); // NOI18N

        LabelUserImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelUserImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assistaff/resources/User.png"))); // NOI18N

        LabelNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        LabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNombre.setText("Nombre Del Empleado");

        LabelTurno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelTurno.setForeground(new java.awt.Color(255, 255, 255));
        LabelTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTurno.setText("Turno");

        javax.swing.GroupLayout PanelCredencialFrontLayout = new javax.swing.GroupLayout(PanelCredencialFront);
        PanelCredencialFront.setLayout(PanelCredencialFrontLayout);
        PanelCredencialFrontLayout.setHorizontalGroup(
            PanelCredencialFrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCredencialFrontLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCredencialFrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelUserImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelCredencialFrontLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(LabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PanelCredencialFrontLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(LabelTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCredencialFrontLayout.setVerticalGroup(
            PanelCredencialFrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCredencialFrontLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(LabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelUserImage, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTurno, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelCredencialBack.setBackground(new java.awt.Color(0, 0, 0));

        LabelQR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assistaff/resources/Codigo QR.png"))); // NOI18N

        javax.swing.GroupLayout PanelCredencialBackLayout = new javax.swing.GroupLayout(PanelCredencialBack);
        PanelCredencialBack.setLayout(PanelCredencialBackLayout);
        PanelCredencialBackLayout.setHorizontalGroup(
            PanelCredencialBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCredencialBackLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(LabelQR, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        PanelCredencialBackLayout.setVerticalGroup(
            PanelCredencialBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCredencialBackLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelQR, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        PanelImprimir.setBackground(new java.awt.Color(21, 100, 191));

        LabelImprimir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelImprimir.setForeground(new java.awt.Color(255, 255, 255));
        LabelImprimir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelImprimir.setText("Imprimir");

        javax.swing.GroupLayout PanelImprimirLayout = new javax.swing.GroupLayout(PanelImprimir);
        PanelImprimir.setLayout(PanelImprimirLayout);
        PanelImprimirLayout.setHorizontalGroup(
            PanelImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImprimirLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(LabelImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        PanelImprimirLayout.setVerticalGroup(
            PanelImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelImprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(PanelCredencialFront, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(PanelCredencialBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addComponent(PanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(PanelImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelCredencialFront, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelCredencialBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(PanelImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICredencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICredencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICredencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICredencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICredencial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCancelar;
    private javax.swing.JLabel LabelImprimir;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelQR;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JLabel LabelTurno;
    private javax.swing.JLabel LabelUserImage;
    private javax.swing.JPanel PanelCancelar;
    private javax.swing.JPanel PanelCredencialBack;
    private javax.swing.JPanel PanelCredencialFront;
    private javax.swing.JPanel PanelImprimir;
    private javax.swing.JPanel PanelTitulo;
    // End of variables declaration//GEN-END:variables
}
