/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.assistaff.GUI;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author yotok
 */
public class GUIInicio extends javax.swing.JFrame {

    /**
     * Creates new form GUIInicio
     */
    GridBagLayout gbl = new  GridBagLayout();
   GUIempleados pnl_empleados;
   GUIpuesto pnl_puestos;
   GUIfechaslaborales pnl_fechas;
     GUIinicio_pestaña pnl_inicio;
    public GUIInicio() {
         
          pnl_empleados = new GUIempleados();
          pnl_puestos = new GUIpuesto();
          pnl_fechas= new GUIfechaslaborales();
          pnl_inicio= new GUIinicio_pestaña();
        URL iconURL = getClass().getResource("../resources/ico.png");
        super.setIconImage(new ImageIcon(iconURL).getImage());
        super.setUndecorated(true);
        initComponents();
        
          panelMaster.setLayout(gbl);
          GridBagConstraints c = new GridBagConstraints();
          c.gridx=0;
          c.gridy=0;
//          panelMaster.add(pnl_empleados,c);
//          panelMaster.add(pnl_puestos,c);
//           panelMaster.add(pnl_fechas,c);
//            panelMaster.add(pnl_inicio,c);
            panelMaster.add(pnl_empleados,c);
          panelMaster.add(pnl_puestos,c);
           panelMaster.add(pnl_fechas,c);
            panelMaster.add(pnl_inicio,c);
          pnl_empleados.setVisible(false);
            pnl_puestos.setVisible(false);
             pnl_fechas.setVisible(false);
              pnl_inicio.setVisible(true);
          
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        jlLogo = new javax.swing.JLabel();
        jlInicio = new javax.swing.JLabel();
        panelActivoInicio = new javax.swing.JPanel();
        jlEmpleados = new javax.swing.JLabel();
        panelActivoEmpleados = new javax.swing.JPanel();
        jlPuestos = new javax.swing.JLabel();
        panelActivoPuestos = new javax.swing.JPanel();
        jlFechasLaboeales = new javax.swing.JLabel();
        panelActivoFechasLaborales = new javax.swing.JPanel();
        panelBarraAzuk = new javax.swing.JPanel();
        panelTitleBar = new javax.swing.JPanel();
        jlTitle = new javax.swing.JLabel();
        jlExit = new javax.swing.JLabel();
        jlMinimize = new javax.swing.JLabel();
        jlSettings = new javax.swing.JLabel();
        panelMaster = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Assistaff - 2018");
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        panelMenu.setBackground(new java.awt.Color(43, 38, 40));
        panelMenu.setForeground(new java.awt.Color(255, 255, 255));
        panelMenu.setPreferredSize(new java.awt.Dimension(320, 720));

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assistaff/resources/LogoForHome.png"))); // NOI18N

        jlInicio.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jlInicio.setForeground(new java.awt.Color(255, 255, 255));
        jlInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assistaff/resources/home.png"))); // NOI18N
        jlInicio.setText("    Inicio");
        jlInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlInicioMouseClicked(evt);
            }
        });

        panelActivoInicio.setBackground(new java.awt.Color(21, 100, 191));

        javax.swing.GroupLayout panelActivoInicioLayout = new javax.swing.GroupLayout(panelActivoInicio);
        panelActivoInicio.setLayout(panelActivoInicioLayout);
        panelActivoInicioLayout.setHorizontalGroup(
            panelActivoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        panelActivoInicioLayout.setVerticalGroup(
            panelActivoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jlEmpleados.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jlEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        jlEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assistaff/resources/users.png"))); // NOI18N
        jlEmpleados.setText("    Empleados");
        jlEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlEmpleadosMouseClicked(evt);
            }
        });

        panelActivoEmpleados.setBackground(new java.awt.Color(21, 100, 191));

        javax.swing.GroupLayout panelActivoEmpleadosLayout = new javax.swing.GroupLayout(panelActivoEmpleados);
        panelActivoEmpleados.setLayout(panelActivoEmpleadosLayout);
        panelActivoEmpleadosLayout.setHorizontalGroup(
            panelActivoEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        panelActivoEmpleadosLayout.setVerticalGroup(
            panelActivoEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jlPuestos.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jlPuestos.setForeground(new java.awt.Color(255, 255, 255));
        jlPuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assistaff/resources/file.png"))); // NOI18N
        jlPuestos.setText("    Puestos");
        jlPuestos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlPuestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlPuestosMouseClicked(evt);
            }
        });

        panelActivoPuestos.setBackground(new java.awt.Color(21, 100, 191));

        javax.swing.GroupLayout panelActivoPuestosLayout = new javax.swing.GroupLayout(panelActivoPuestos);
        panelActivoPuestos.setLayout(panelActivoPuestosLayout);
        panelActivoPuestosLayout.setHorizontalGroup(
            panelActivoPuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        panelActivoPuestosLayout.setVerticalGroup(
            panelActivoPuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jlFechasLaboeales.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jlFechasLaboeales.setForeground(new java.awt.Color(255, 255, 255));
        jlFechasLaboeales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assistaff/resources/calendar.png"))); // NOI18N
        jlFechasLaboeales.setText("    Fechas laborales");
        jlFechasLaboeales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlFechasLaboeales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlFechasLaboealesMouseClicked(evt);
            }
        });

        panelActivoFechasLaborales.setBackground(new java.awt.Color(21, 100, 191));

        javax.swing.GroupLayout panelActivoFechasLaboralesLayout = new javax.swing.GroupLayout(panelActivoFechasLaborales);
        panelActivoFechasLaborales.setLayout(panelActivoFechasLaboralesLayout);
        panelActivoFechasLaboralesLayout.setHorizontalGroup(
            panelActivoFechasLaboralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        panelActivoFechasLaboralesLayout.setVerticalGroup(
            panelActivoFechasLaboralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelMenuLayout.createSequentialGroup()
                            .addComponent(panelActivoPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(jlPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addComponent(panelActivoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jlInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addComponent(panelActivoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jlEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addComponent(panelActivoFechasLaborales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jlFechasLaboeales, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jlLogo)
                .addGap(80, 80, 80)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelActivoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelActivoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelActivoPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlFechasLaboeales, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelActivoFechasLaborales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        panelBarraAzuk.setBackground(new java.awt.Color(21, 100, 191));
        panelBarraAzuk.setMaximumSize(new java.awt.Dimension(960, 16));
        panelBarraAzuk.setMinimumSize(new java.awt.Dimension(960, 16));
        panelBarraAzuk.setPreferredSize(new java.awt.Dimension(960, 16));

        javax.swing.GroupLayout panelBarraAzukLayout = new javax.swing.GroupLayout(panelBarraAzuk);
        panelBarraAzuk.setLayout(panelBarraAzukLayout);
        panelBarraAzukLayout.setHorizontalGroup(
            panelBarraAzukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelBarraAzukLayout.setVerticalGroup(
            panelBarraAzukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        panelTitleBar.setBackground(new java.awt.Color(255, 255, 255));
        panelTitleBar.setMaximumSize(new java.awt.Dimension(960, 64));
        panelTitleBar.setMinimumSize(new java.awt.Dimension(960, 64));
        panelTitleBar.setPreferredSize(new java.awt.Dimension(960, 64));

        jlTitle.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(102, 100, 98));
        jlTitle.setText("Assistaff - 2018");

        jlExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assistaff/resources/cancel_gray.png"))); // NOI18N
        jlExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlExitMouseClicked(evt);
            }
        });

        jlMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assistaff/resources/minus-symbol_gray.png"))); // NOI18N
        jlMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMinimizeMouseClicked(evt);
            }
        });

        jlSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assistaff/resources/sign-in.png"))); // NOI18N
        jlSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelTitleBarLayout = new javax.swing.GroupLayout(panelTitleBar);
        panelTitleBar.setLayout(panelTitleBarLayout);
        panelTitleBarLayout.setHorizontalGroup(
            panelTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleBarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jlTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 626, Short.MAX_VALUE)
                .addComponent(jlSettings)
                .addGap(16, 16, 16)
                .addComponent(jlMinimize)
                .addGap(16, 16, 16)
                .addComponent(jlExit)
                .addGap(16, 16, 16))
        );
        panelTitleBarLayout.setVerticalGroup(
            panelTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleBarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSettings)
                    .addComponent(jlMinimize)
                    .addComponent(jlExit)
                    .addComponent(jlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelMaster.setBackground(new java.awt.Color(255, 255, 255));
        panelMaster.setMaximumSize(new java.awt.Dimension(960, 640));
        panelMaster.setMinimumSize(new java.awt.Dimension(960, 640));
        panelMaster.setName(""); // NOI18N

        javax.swing.GroupLayout panelMasterLayout = new javax.swing.GroupLayout(panelMaster);
        panelMaster.setLayout(panelMasterLayout);
        panelMasterLayout.setHorizontalGroup(
            panelMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelMasterLayout.setVerticalGroup(
            panelMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBarraAzuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelBarraAzuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(panelTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(panelMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jlExitMouseClicked

    private void jlMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizeMouseClicked
        // TODO add your handling code here:
        super.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jlMinimizeMouseClicked

    private void jlEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlEmpleadosMouseClicked
 pnl_empleados.setVisible(true);
            pnl_puestos.setVisible(false);
            pnl_fechas.setVisible(false);
            pnl_inicio.setVisible(false);
    }//GEN-LAST:event_jlEmpleadosMouseClicked

    private void jlPuestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlPuestosMouseClicked
       pnl_empleados.setVisible(false);
            pnl_puestos.setVisible(true);
            pnl_fechas.setVisible(false);
             pnl_inicio.setVisible(false);
    }//GEN-LAST:event_jlPuestosMouseClicked

    private void jlFechasLaboealesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlFechasLaboealesMouseClicked
         pnl_empleados.setVisible(false);
            pnl_puestos.setVisible(false);
              pnl_fechas.setVisible(true);
               pnl_inicio.setVisible(false);
    }//GEN-LAST:event_jlFechasLaboealesMouseClicked

    private void jlInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInicioMouseClicked
        pnl_empleados.setVisible(false);
            pnl_puestos.setVisible(false);
              pnl_fechas.setVisible(false);
               pnl_inicio.setVisible(true);
    }//GEN-LAST:event_jlInicioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlEmpleados;
    private javax.swing.JLabel jlExit;
    private javax.swing.JLabel jlFechasLaboeales;
    private javax.swing.JLabel jlInicio;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlMinimize;
    private javax.swing.JLabel jlPuestos;
    private javax.swing.JLabel jlSettings;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JPanel panelActivoEmpleados;
    private javax.swing.JPanel panelActivoFechasLaborales;
    private javax.swing.JPanel panelActivoInicio;
    private javax.swing.JPanel panelActivoPuestos;
    private javax.swing.JPanel panelBarraAzuk;
    private javax.swing.JPanel panelMaster;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelTitleBar;
    // End of variables declaration//GEN-END:variables
}
